modLoader="javafml"
loaderVersion="[40,)"
license="ARR"

[[mods]]
modId="chemlib"
version="${file.jarVersion}"
displayName="ChemLib"
logoFile=""
authors="DarkArcana"
description='''
ChemLib provides all of the elements of the periodic table and many compounds of those elements. It also includes some items based on the elements and compounds such as ingots and lamps.
'''
[[dependencies.chemlib]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.54,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chemlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
